### ISSUE TITLE
Low / High tarrifs

### ISSUE THREAD

**Issue by JohanBraeken** [bram2202/esp8266-dsmr#10]
Hi there,

Not a bug, but something to be aware of:

In Belgium we use a DMSR variant too for smartmeters, however, the "low" and "high" tariffs have the reversed numbering. (And it is called "Day" and "Night" for historical reasons.)
In the future, the amount of different tariffs can (will?) also be increased.

So, to be future proof, it might not be a good idea to have a fixed association between the tariff number and the MQTT topic used (low / high).

**Comment by bram2202** [comment]
@JohanBraeken Do you have any documentation or examples of this variant.
I

**Comment by JohanBraeken** [comment]
The Belgian variant is based on the Dutch one.
P1 hardware interface is identical, P1 messages are mostly the same.

The differences, and some examples, can be found in the documentation at this site: [https://maakjemeterslim.be/aanbieder](https://maakjemeterslim.be/aanbieder)
The site and documentation is only available in Dutch, French and German, but I assumme Dutch shouldn't be an issue. :-)

There are multiple versions in use simulteniously and you can't assume smart meters will be upgraded to the newest version. (Version is available in P1 message.)
