### ISSUE TITLE
Software Arduino

### ISSUE THREAD

**Issue by QFaas** [bram2202/esp8266-dsmr#20]
Hoi Bram,
Ik heb eens een vraagje, ik heb proberen je Github over ESP8266-dsmr proberen namaken, het is mij tot in alle hardware gelukt dit 1 op 1 te kopieren en volgens het schema te zetten. Alleen nu loop ik zelf klein beetje stuk op het gedeelte van Arduino, ik heb alle bestanden gekopieerd van deze Github maar ik zat eens te kijken in het hoofd Arduino bestand (esp8266-dsmr.ino) daarin staan nog enkele bestanden maar die niet te vinden zijn in jou Github over ESP8266-dsmr. Nu hebben wij eens gezocht op internet die bestanden zijn inderdaad ergens te vinden maar al die andere bestanden bevatten ook nog een andere 'include' maar wij weten totaal niet of deze bestanden er allemaal in horen. Zou je eens contact met mij willen opnemen om mij verder wegwijs te helpen.
Ik hoop voldoende info te hebben gegeven en mij hierbij verder wil helpen ;).
Gr,

Quinten

**Comment by QFaas** [comment]
Ik hoop dat je mij hiermee zo snel mogelijk kan helpen omdat het een relatieve korte deadline heeft :()

**Comment by bram2202** [comment]
Hey.

Ik ga er van uit dat je de includes bedoeld zoals `ESP8266WiFi.h`?

Onder het kopje [library-dependencies](https://github.com/bram2202/esp8266-dsmr#library-dependencies) zie je welke libraries er gebruikt zijn, 
deze zijn de installeren in de Arduino tool -> `Tools` -> `Library Manager`.

**Comment by QFaas** [comment]
Ja dat bedoel ik inderdaad,
Maar die library dependescies moet je daar alle bestanden van kopiëren of
wat is de bedoeling?


Op do 2 dec. 2021 13:45 schreef Bram van Deventer ***@***.***

**Comment by bram2202** [comment]
Nee, via de `Library Manager` download je ze in een folder van de Arduino IDE zelf, bij het bouwen haalt hij ze daar uit.
Je kan zelf de folder aanmaken en files kopiëren, maar via de manager is makkelijker.

**Comment by bram2202** [comment]
https://www.arduino.cc/en/Guide/Libraries

**Comment by QFaas** [comment]
Deze site moet ik alle libraries halen want ik keek in esp8266wifi.h maar in dat bestand staan nog bestanden met include in?Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bram van Deventer ***@***.***> Datum: 02-12-2021  14:47  (GMT+01:00) Aan: bram2202/esp8266-dsmr ***@***.***> Cc: QFaas ***@***.***>, Author ***@***.***> Onderwerp: Re: [bram2202/esp8266-dsmr] Software Arduino (Issue #20) 
https://www.arduino.cc/en/Guide/Libraries

**Comment by QFaas** [comment]
Hoi bram, zou je misschien contact met mij kunnen opnemen om misschien het een klein beetje te verduidelijken?Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bram van Deventer ***@***.***> Datum: 02-12-2021  14:47  (GMT+01:00) Aan: bram2202/esp8266-dsmr ***@***.***> Cc: QFaas ***@***.***>, Author ***@***.***> Onderwerp: Re: [bram2202/esp8266-dsmr] Software Arduino (Issue #20) 
https://www.arduino.cc/en/Guide/Libraries

**Comment by QFaas** [comment]
Hallo Bram,
Wij hebben inderdaad de library kunnen toevoegen over de PubSubClient die heeft ie gevonden maar de library over Core For ESP8266 kunnen wij niet vinden hoe jij hebt beschreven in Arduino, enig idee?
Gr Quinten

**Comment by bram2202** [comment]
Als kijkt op de pagina van de Core lib: https://github.com/esp8266/Arduino
Staat er boven aan `Installing with Boards Manager`, die stappen moet je volgen.

**Comment by QFaas** [comment]
Als wij op Verifieren klikken krijgen wij de melding dat het bestand ESP8266Wifi.h: no Such file in directory

**Comment by QFaas** [comment]
Hoe krijgen wij dit voor elkaar wanneer arduino dit bestand wel pakt?

**Comment by bram2202** [comment]
Reboot?

**Comment by QFaas** [comment]
Dit werkt helaas niet, we krijgen wel dezelfde melding maar dan met ArduinoJSON.h: no Such file in directory
Moeten wij hier nog iets specifieks voor doen?
Ps, sorry voor alle vragen :P

**Comment by QFaas** [comment]
Wij willen gewoon graag dat het werkt vandaar

**Comment by bram2202** [comment]
Ik zie dat er nog een lib mist in mijn readme.
Maar als je je foutmelding in  [google gooit](https://letmegooglethat.com/?q=+ArduinoJSON.h%3A+no+Such+file+in+directory)
Dan zie je dat je die ook moet toevoegen in de `Library Manager`

**Comment by QFaas** [comment]
Dit hebben wij nu gedaan, maar nu worden er fouten aangegeven die in de ArduinoJson code zitten? kan dit misschien zijn voor een verkeerde library of niet?

**Comment by QFaas** [comment]
wij hebben nameljik de 6.18.5 library gedownload van ArduinoJSON

**Comment by bram2202** [comment]
Ik heb hier ook de 6.18.5 versie geprobeerd, en ik kan gewoon builden.
Welke foutmeldingen krijg je?

**Comment by QFaas** [comment]
Dag bram, het is gelukt de codering kwamen geen foutmeldingen meer maar in het ino bestand staat er 2 verschillende pinnen zoals lvlpin en en rx pin, wat houd die lvl pin in? De aansluitingen met de jumpwires hebben wij gezet op d1(dezelfde pin als op wemos), RX, d7, 3.3v of 5v(vin) en gndVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bram van Deventer ***@***.***> Datum: 03-12-2021  15:04  (GMT+01:00) Aan: bram2202/esp8266-dsmr ***@***.***> Cc: QFaas ***@***.***>, Author ***@***.***> Onderwerp: Re: [bram2202/esp8266-dsmr] Software Arduino (Issue #20) 
Ik heb hier ook de 6.18.5 versie geprobeerd, en ik kan gewoon builden.
Welke foutmeldingen krijg je?

**Comment by QFaas** [comment]
Hoi Bram, ik heb de code nu werkend, maar ik heb 1 ander klein probleempje, en dat is dat ik de esp8266 niet kan vinden op het netwerk dus zo ook niet aan mijn Home Assistant kan toevoegen heb je enig idee?

**Comment by QFaas** [comment]
de code is trouwens geupload naar de esp met de Settings.h ingevuld

**Comment by QFaas** [comment]
Dag Bram, ik kreeg hem inderdaad op het netwerk (voor heel even), toen heb ik hem eruit gedaan omdat ik naar de P1 poort moest gaan, maar daarna is hij niet meer op het netwerk gekomen, enig idee? want hij komt nu ook niet meer op de router als een wireless client etc... Hoe kan ik dit oplossen dat hij altijd op het netwerk blijft?

**Comment by QFaas** [comment]
Bram ik heb nu alles werkend, code, dat hij op het netwerk gevonden wordt, alleen hoe kan je hem nu toevoegen in je Home Assistant, ik heb geprobeerd via MQTT broker in home assistant integratie, dit zonder resultaat, ik heb ook geprobeerd om via de integratie om via de DSMR Slimme Meter integratie te proberen dit ook zonder resultaat, enig idee?

**Comment by bram2202** [comment]
Goed om te horen dat je het toch werkend hebt gekregen.
Je hebt inderdaad een losse MQTT broker nodig, de gegevens daarvan (ip/poort/user/password) moet je dan instellen in de config file.
Je kan met een programma zoals [MQTT-Explorer](https://github.com/thomasnordquist/MQTT-Explorer) kijken of er überhaupt wel een bericht op het topic wordt gezet.

**Comment by QFaas** [comment]
Die losse mqtt broker, moet je dat instellen in het kopje settings.h, maar
de vraag is dus hoe kan ik dit in home assistant krijgen?


Op zo 5 dec. 2021 12:27 schreef Bram van Deventer ***@***.***

**Comment by bram2202** [comment]
je kan elke topic als een sensor in je home assistant yaml zetten:

https://www.home-assistant.io/integrations/sensor.mqtt/

**Comment by QFaas** [comment]
Dus je zegt eerst dat ik nog een yaml file miet maken?


Op zo 5 dec. 2021 14:23 schreef Bram van Deventer ***@***.***

**Comment by QFaas** [comment]
Bram, wij willen de esp graag toevoegen ofja de entitities etc, via MQTT Mosquitto broker, maar dan krijgen we het deel van verbindgegevens,
-Broker (Wat moet hier staan?)
-Poort (Hebben wij 1883)
-Gebruikersnaam
-wachtwoord
Dit hebben wij allemaal toegevoegd daarna komt hij op iets waar je de QoS kan toevoegen als wij next klikken zou het goed moeten staan maar dan kan je publiceer een onderwerp aanklikken en dan komen wij niet verder heb jij toevallig enig idee?
Zoja wat doen wij fout of wat heb jij gedaan om je esp in Home Assistant te krijgen.

**Comment by bram2202** [comment]
Broker komt je IP van de MQTT broker.
QoS kan je gewoon default laten.

Heb je met een ander mqtt tool gekeken of de ESP überhaupt iets op de bus gooit?

**Comment by QFaas** [comment]
Hoi Bram, Geen andere tool gebruikt want HA kent er maar 1 op dit moment volgens mij en dat is die Mosquitto Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bram van Deventer ***@***.***> Datum: 07-12-2021  15:11  (GMT+01:00) Aan: bram2202/esp8266-dsmr ***@***.***> Cc: QFaas ***@***.***>, Author ***@***.***> Onderwerp: Re: [bram2202/esp8266-dsmr] Software Arduino (Issue #20) 

Broker komt je IP van de MQTT broker.

QoS kan je gewoon default laten.

Heb je met een ander mqtt tool gekeken of de ESP überhaupt iets op de bus gooit?

**Comment by QFaas** [comment]
Bram, misschien een gekke vraag hoor maar heb je toevallig iets van Teams of Discord zodat ik het eventueel eens kan laten zien, misschien zie jij iets wat er moet veranderd worden of bij moetVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bram van Deventer ***@***.***> Datum: 07-12-2021  15:11  (GMT+01:00) Aan: bram2202/esp8266-dsmr ***@***.***> Cc: QFaas ***@***.***>, Author ***@***.***> Onderwerp: Re: [bram2202/esp8266-dsmr] Software Arduino (Issue #20) 

Broker komt je IP van de MQTT broker.

QoS kan je gewoon default laten.

Heb je met een ander mqtt tool gekeken of de ESP überhaupt iets op de bus gooit?

**Comment by QFaas** [comment]
Bram, misschien een gekke vraag hoor maar heb je toevallig iets van Teams of Discord zodat ik het eventueel eens kan laten zien, misschien zie jij iets wat er moet veranderd worden of bij moet

**Comment by QFaas** [comment]
ik zie namelijk in mijn router dat de esp het juiste ip krijgt dan wat ik in het Settings.h file heb

**Comment by bram2202** [comment]
Ik heb geen Teams of Discord.

Het IP adres van je ESP zou iets anders moeten zijn dat wat er in de settings.h staat, hier staat het IP adres van je broker.
Dit zijn twee verschillende dingen.

Zoals ik al eerder zei:
>  Je kan met een programma zoals [MQTT-Explorer](https://github.com/thomasnordquist/MQTT-Explorer) kijken of er überhaupt wel een bericht op het topic wordt gezet.

Zo weet je of de ESP wel of geen berichte stuurt, en kan je beter pinpointen waar het probleem zit (esp / broker / HA)

**Comment by QFaas** [comment]
Hoi Bram, we hebben gister getest, mijn leraar ook, de mqtt in home assistant kan gevonden worden (dit is getest etc), ook de esp zelf wordt gevonden op het netwerk met die mqtt exploreer, alleen het lijkt dat de mqtt niet het signaal doorstuurd naar bijvoorbeeld de Home Assistant, en zo dus geen mqtt topics kan ophalen. WIj hebben nog gekeken in de code maar kunnen zelf niet heel veel vinden waar het aan licht.
Heb jij nu enig idee, en welke libraries heb jij gebruikt in je arduino? misschien licht het daaraan?

**Comment by QFaas** [comment]
dus we denken dat het in de esp code zit het probleem

**Comment by spmvanmierlo** [comment]
Hoi Quinten,

Bij mij werkt alles naar behoren, dus het lijkt erop dat je configuratie niet in orde is.

Zou je een screenshot kunnen delen van de mqtt explorer wanneer deze verbonden is met de ESP?

**Comment by QFaas** [comment]
Hoi Sjors, tijdens de mqtt explorer wordt het ip van de esp wel gevonden maar geen topics ofja mijn vraag is dus hoe ziet die van jou er ongeveer uit?

**Comment by QFaas** [comment]
licht het er misschien aan dat wij het bestand settings.h niet goed maken of?
aan wat zou het nog kunnen liggen?

**Comment by bram2202** [comment]
Wil je je settings eens delen?

**Comment by spmvanmierlo** [comment]
Zoals je kunt zien komt er van alles binnen op de mqtt broker...

![Explorer](https://user-images.githubusercontent.com/8707768/145411558-ba098d9b-4881-4922-b572-3feb7ad89438.png)

Ik stel voor dat je al je instellingen even deelt aan de hand van screenshots. Dus je instellingen van Home assistant, mosquito broker, esp settings etc.

Nu hebben we te weinig informatie om je te helpen.

**Comment by QFaas** [comment]
In het bestand settings.h
Hostname: "ESP-DSMR"
WIFI_SSID: "(mijn netwerk"
WIFI_PASSWORD: "(Mijn netwerk ww)"
MQTT_BROKER: "(Het ip adres van de home assistant waar die bij mij op draait)"
MQTT_PORT: 1883
MQTT_USER: "(Naam 2e account van mijn Home Assistant)"
MQTT_PASSWORD: "(Wachtwoord van 2e account van mijn home assistant)"
AUTOCONFIG_GAS: true
AUTOCONFIG_POWER_EXTENDED: true
LOG_LEVEL INFO

zo staat et er bij ons in

**Comment by QFaas** [comment]
welke settings wil je nog weten in Home Assistant?

**Comment by spmvanmierlo** [comment]
> 

Je Mosquitto broker - configuratie

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145413235-d8d5b3fd-22d6-4221-a299-09023c9584e7.png)
![image](https://user-images.githubusercontent.com/95419525/145413274-86714212-de5e-4a5b-b65c-2a05a2e504a6.png)

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145413430-ab015c11-caf6-47a0-ae98-bcb678e540f4.png)

**Comment by QFaas** [comment]
Hebben jullie hier meer aan?

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145413842-1678a3d2-3b4e-49a8-9188-560c1af3ef13.png)



Dit is als ik al deze stappen heb gedaan

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145414303-2ecffdae-1c55-40f3-9b6d-cd9bcded5e7a.png)


Dit heb ik als logboek met mqtt

**Comment by QFaas** [comment]
dat is inderdaad het ip van de esp wat hij aangeeft die 107 dat zie ik in mijn netwerk

**Comment by bram2202** [comment]
Welke waardes zitten in "power_consumption"?
lijkt er op dat hij alleen online door geeft, en geen values

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145414751-a7545831-ab5a-4999-bc2d-fde337256d0a.png)


dit geeft hij aan als ik erop klik

**Comment by bram2202** [comment]
ja, de ESP heeft geen waardes ontvangen.

Waar heb je hem ingeprikt, ondersteund deze DSMR? 
En hoe ziet je circuit er uit?

**Comment by QFaas** [comment]
het is dsmr 4
het circuit ziet eruit als diegene die in het schema van jou staat

**Comment by bram2202** [comment]
Zou je daar een foto van kunnen maken?

**Comment by QFaas** [comment]
alleen 1 klein dingetje dat zit op een breadboard, dus weet niet of het zo makkelijk te zien is op foto :(

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145416201-a72c03b4-6f70-46cb-b5a2-2a5e9f5d3d42.png)

dit is het aansluitschema in schets, ik zal zo nog een foto maken

**Comment by QFaas** [comment]
Verzonden vanaf mijn Galaxy

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145417034-5a7b8379-9ba7-48bd-998f-37c54123f1ce.png)

**Comment by QFaas** [comment]
sorry maar het is vrij lastig om een foto te maken van zoveel kabels door elkaar

**Comment by QFaas** [comment]
maar dat plaatje met dat breadboard erop met RX etc is hoe wij het hebben nagemaakt maar dan met natuurlijk niet van die hele lange ijzeren dingen natuurlijk :P

**Comment by bram2202** [comment]
Dat is inderdaad lastig te zien zo.
Kan je van je verbinding met de DSMR meten tussen pin1 en pin6 of dit `+5v` of `-5v` is?

**Comment by QFaas** [comment]
wacht
pin 1 en pin 6 is?

**Comment by QFaas** [comment]
lijkt mij VIN POORT en GND, klopt dit?

**Comment by bram2202** [comment]
Klopt, maar dit moet je dan even meten zonder dat de rest van het circuit er aan hangt, echt alleen de DSMR zelf.
Dit om er zeker van te zijn dat het geheel niet omgedraaid zit.

**Comment by QFaas** [comment]
is goed ik ga even meten ik laat het zo weten

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145422481-738b4f6a-715b-4d5c-99a4-ef31f9c74956.png)

Ik heb net proberen meten maar ik krijg geen 5v terug op het scherm hoor misschien dat ik het verkeerd heb aangesloten?

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145424886-1becf56b-0704-46f7-8354-4566e1b4567a.png)


het Zou deze moeten zijn kweet niet of je hier wat aan hebt

**Comment by QFaas** [comment]
ik heb het probleem gevonden denk ik bram, op mijn esp meet de VIN poort maar 0.18 max dus ik denk dat die poort gewoon kapot is, en omdat ik een dsmr 4.0 heb kan die niet zelf voeden en moet er een 5v aan maar omdat hij het niet doet kan hij inderdaad alleen aan maar geen data etc ontvangen

**Comment by QFaas** [comment]
en die werkt niet, dus ik ga kijken of ik een nieuwe esp8266 chip mee kan krijgen zodat ik het kan zien dat de 5v werkt

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145485353-b643d54f-1312-48de-8137-cea25fc5f3e4.png)

**Comment by bram2202** [comment]
> ik heb het probleem gevonden denk ik bram, op mijn esp meet de VIN poort maar 0.18 max dus ik denk dat die poort gewoon kapot is, en omdat ik een dsmr 4.0 heb kan die niet zelf voeden en moet er een 5v aan maar omdat hij het niet doet kan hij inderdaad alleen aan maar geen data etc ontvangen

Ik bedoelde pin 1 en 6 van je DSMR aansluiting niet van je ESP.
Het zou misschien kunnen dat je deze aansluiting andersom hebt gemaakt, dus pin 1 == 6, 2 == 5 etc..

Als je een USB kabel aan je ESP hebt hangen zou dit voldoende moeten zijn.

**Comment by QFaas** [comment]
sorry maar had je vraag verkeerd begrepen ik zal vandaag eens kijken

**Comment by QFaas** [comment]
Alleen een ander vraagje Bram, in jou schema staat ook Enable RX, en RX,  die Enable RX waarvoor staat die, ik heb hem namelijk op D7 staan (dat is en andere RX) maar wat is dat bij jou

**Comment by QFaas** [comment]
Bram ik heb net gemeten er komt 5v door pin 1 en 6 zo te zien in mijn dsmr

**Comment by QFaas** [comment]
En nog een ander dingetje, ik heb nu die nieuwe esp, alleen die komt weer totaal niet snel in de mqtt hoe kan ik dit probleem oplossen?

**Comment by bram2202** [comment]
`Enable RX` zorgt er voor dat de levelshifter gaat werken (het 5v signaal omzetten naar 3.3v), zo wordt de ESP niet opgeblazen.
Officieel zou die alleen 3.3v input kunnen hebben.

Die pin waar `Enable RX` op zit moet dus wel HOOG zijn, anders komt de data niet door.
Ik weet niet of de pin nummer tussen een ESP8266 en ESP32 overeen komen.

**Comment by QFaas** [comment]
je hebt zelf de wemos gepakt dit is op basis van 8266?

**Comment by QFaas** [comment]
Niet?

**Comment by QFaas** [comment]
De chip zelf al is geflashed, dus daaraan kan het niet liggen, maar het rare is ook dat ik probeer de code via poort 1 maar die pakt die niet, dus hhij ziet het niet als poort, terwijl die andere esp (die 5v kapot is) die pakt die wel

**Comment by QFaas** [comment]
![image](https://user-images.githubusercontent.com/95419525/145613880-3de47047-09b8-4dc4-9cc2-e836e50f1995.png)

**Comment by bram2202** [comment]
Hallo Quinten,

De laatste genoemde problemen lijkt om een drive issue.
De code zoals hij nu op Git staat werkt (geverifieerd) als er geen data binnen komt op de ESP tijdens debuggen moet je toch nog maar eens goed kijken naar de gebruikte pinnen in de code en die op je ESP.

success.
