### ISSUE TITLE
Gas not working and has the wrong label

### ISSUE THREAD

**Issue by Dutchone** [bram2202/esp8266-dsmr#21]
Hi,

I build the pcb as noted in the files,

But i cant get the gas to read, it makes the sensor but no data is presented, i tested it with my old p1 monitor, and that works with the same key adress.

Any idea what is going wrong?

Also gas is noted as kWh but has to be M³.

Nick

**Comment by bram2202** [comment]
Hey Nick,

Are any of the other P1 values (power) being send ?
The unit is indeed wrong.

**Comment by Dutchone** [comment]
Hey Bram,

Yes everything for a L1 meter is coming through, so i suspect its a telegram error somewhere.

I suspect the unique name is gas/total. The name is total_gas.

But for other messages the unique name is phase_3_peak, and not phase/3/peak

**Comment by Dutchone** [comment]
Hi Bram,

Dit a bit more of a deep dive with mqtt explorer, Gas telegrams are being send only in HA they are not reading.

Just to keep you updated.

**Comment by Dutchone** [comment]
Well After a quick update if found the problem,

There is a Slash missing.

What is in the github:
 autoconfPayload["availability_topic"] = _identifier + "gas/total/status";

What is should be:
 autoconfPayload["availability_topic"] = _identifier + "/gas/total/status";

Thats why HA is looking in the wrong topic
ESP_DSMR_1994BDgas/total/status

And not in "ESP_DSMR_1994BD/gas/total/status" as is should be

    if (AUTOCONFIG_GAS)
    {
        // Gas
        autoconfPayload["device"] = device.as<JsonObject>();
        autoconfPayload["availability_topic"] = _identifier + "/gas/total/status";
        autoconfPayload["state_topic"] = _identifier + "/gas/total";
        autoconfPayload["last_reset_topic"] = _identifier + "/gas/total/reset";
        autoconfPayload["name"] = _identifier + "_total_gas";
        autoconfPayload["unit_of_measurement"] = "m³";
        autoconfPayload["unique_id"] = "gas_total";
        autoconfPayload["icon"] = "mdi:counter";
        autoconfPayload["last_reset_value_template"] = "1970-01-01T00:00:00+00:00";
        serializeJson(autoconfPayload, mqttPayload);
        _mqttPublisher.publish("homeassistant/sensor/" + _identifier + "/total_gas/config", &mqttPayload[0], false);
        autoconfPayload.clear();
    }
}

**Comment by bram2202** [comment]
Ah my bad, can you commit your code and create Pull Request for this?

**Comment by Dutchone** [comment]
Nah I'm already thankfull you made this, 

When I have time I will try, since I never made a pull before.
