### ISSUE TITLE
MQTT komt niet in beeld

### ISSUE THREAD

**Issue by QFaas** [bram2202/esp8266-dsmr#24]
Hoi Bram, ik heb de chip weer aan de praat gekregen met de juiste mqtt gegevens erop, maar hij komt wederom niet in home Assistant, en ook niet in de mqtt explorer?

**Comment by QFaas** [comment]
kan dit misschien komen omdat ik een virtuele machine gebruik voor mijn home assistant?

**Comment by bram2202** [comment]
Hallo Quinten,

Deze vragen hebben niets meer te maken het dit Github project zelf.

Ik wil je best helpen maar een issue aanmaken is hiervoor niet de juiste manier, 
daarvoor zijn bijvoorbeeld [Stackoverflow](https://stackoverflow.com/) of nog beter de [HA community](https://community.home-assistant.io/).
Als je hier je vragen op post kan iedereen die wil er op reageren, en ben je niet afhankelijk van 1 persoon.

Maar misschien is het verstandig om eerst even zelf onderzoek te doen naar hoe MQTT werkt en wat de beperkingen zijn i.p.v. elke vraag zo maar de posten als een issue, en een kant en klaar antwoord te verwachten. 
Veel van je vragen zijn al eens door iemand gesteld en zijn te vinden als je Google gebruikt, Stackoverflow is hierin een handige en betrouwbare bron.

Succes

**Comment by QFaas** [comment]
Bram, ik snap dat ik niet alles moet vragen maar dit gaat wel over het GitHub project want als ik alles 1 op 1 hetzelfde gedaan heb als in jou GitHub is dit toch raar dat dit bij mij niet werkt en bij jou wel? Daarover gaan deze vragen... want de MQTT staat immers wel in jou GitHub, dus vandaar dat ik daar vragen over aan het stellen ben..

**Comment by QFaas** [comment]
Dus de vraag die nu dan bovenop komt, welke libraries heb je precies allemaal gedownload voor dit Project in Arduino, want ik krijg het idee dat wij misschien verkeerde libraries hebben gedownload en dat het daar misschien aan licht.

**Comment by QFaas** [comment]
En het klopt sommige dingen gaat niet over het GitHub project maar ik dacht jij bent hier ook in aanraking mee gekomen dus misschien weet je dat wel
